name: "Alex Pearson's Blog"
description: "Thoughts on building, breaking, programming, educating, sometimes lifting, and everything in between. "

url: "http://alexpear.com/blog"

paginate: 15

markdown: rdiscount
permalink: :year/:month/:day/:title/
