name: "Alex Pearson's Blog"
description: "Thoughts on building, breaking, programming, educating, sometimes lifting, and everything in between. "

url: "http://alexpear.com/blog"

paginate: 15

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highliter: rouge

permalink: :year/:month/:day/:title/

encoding: 'utf-8'
